// These styles apply to every route in the application
import "./output.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="back-drop"></div>
        {children}
      </body>
    </html>
  );
}
