// These styles apply to every route in the application
import "./output.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-black mx-auto max-w-[1440px]">
        <div id="back-drop"></div>
        <div id="root">{children}</div>
      </body>
    </html>
  );
}
