export const ProjectData = [
  {
    imageSrc: "/ProjectPic/freelancing1.png",
    imageAlt: "UberEats_Clone",
    techStack: [
      "Typescript",
      "Next.js",
      "Node.js",
      "Express.js",
      "TailwindCSS",
      "PostgreSQL",
    ],
    hoverText1: "Freelance",
    hoverText2: "Work",
    styles: "",
    projectName: "Freelance Work I",
    content: [
      "Collaborated with a henna artist client to address appointment management challenges, ensuring bookings within a week.",
      "Implemented a Twilio-based phone number verification system for streamlined user experience.",
      "Created a dynamic appointment scheduling system with PostgreSQL database and cronJob optimization.",
    ],
    liveLink: "https://charmsofmehandi.com/",
  },
  {
    imageSrc: "/ProjectPic/progress-glass.png",
    imageAlt: "UberEats_Clone",
    techStack: ["Next.js", "TailwindCSS", "Framer Motion"],
    hoverText1: "Freelance",
    hoverText2: "Work",
    styles: "",
    projectName: "Freelance Work II",
    content: [
      "Designed and developed an aesthetically pleasing website for a glass repair company.",
      "Automated email notifications for quote requests through the website.",
      "Implemented smooth, natural animations using Framer Motion.",
    ],
    liveLink: "https://progressglass.ca/",
  },
  {
    imageSrc:
      "https://images.unsplash.com/photo-1554672408-758865e7274a?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageAlt: "UberEats_Clone",
    techStack: [
      "Typescript",
      "React",
      "React Router",
      "Redux",
      "Firebase",
      "TailwindCSS",
    ],
    hoverText1: "Practice",
    hoverText2: "Project",
    styles: "",
    projectName: "Uber Eats Clone",
    content: [
      "Focused on gaining hands-on experience with TypeScript, Firebase and React libraries through project development.",
      "Implemented restaurant listings with menus for multiple stores, including special offers, favorite store selection, and detailed order history.",
    ],
    liveLink: "https://reactiverse-2842e.web.app/",
    codeLink: "https://github.com/MandeepPaul/Uber-Eats-Clone",
  },
  {
    imageSrc: "/ProjectPic/meetup.jpg",
    imageAlt: "ReactEvents",
    techStack: [
      "Node.js",
      "Express.js",
      "React",
      "React Router",
      "React Query",
      "CSS",
    ],
    hoverText1: "Practice",
    hoverText2: "Project",
    projectName: "React Events App",
    content: [
      "Built a React Events app for practical experience in React, React Router, and exploring crucial React Query concepts like caching, stale time and mutations.",
      "Reduced API calls by 30% and improved application loading times by 20% by implementing React Query's caching and optimized data fetching in the React Events app.",
    ],
    liveLink: "",
    codeLink:
      "https://github.com/MandeepPaul/Reactiverse/tree/main/react-query",
  },
];
